version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00" # Optional: Set a specific time (UTC)
    target-branch: "master" # Your default branch
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"