name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get release tag version
        id: get_version
        run: |
          # Extract version from GitHub ref (remove 'refs/tags/' prefix and any 'v' prefix)
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          TAG_VERSION=${TAG_VERSION#v}
          echo "VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo "Using release version: $TAG_VERSION"

      - name: Update version in pom.xml
        run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }} -DgenerateBackupPoms=false

      - name: Build with version
        run: mvn package -DskipTests

      - name: Generate Javadoc JAR
        run: mvn javadoc:jar -DskipTests

      - name: Generate Sources JAR
        run: mvn source:jar -DskipTests

      - name: Upload JAR to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/geojson-jackson-${{ steps.get_version.outputs.VERSION }}.jar
            target/geojson-jackson-${{ steps.get_version.outputs.VERSION }}-javadoc.jar
            target/geojson-jackson-${{ steps.get_version.outputs.VERSION }}-sources.jar
            pom.xml
